base_path: /
resources:
  - users
  - payments
  - providers
  - bills
  - salaries
  - occupations
  - employees
  - reports
  - sellers
  - sells
  - accounts
  - roles
routes:
  index: [/,App\Controllers\homeController.index,GET]
  delete_users: [/users,\App\Controllers\usersController.deleteAll,DELETE]
  delete_employees: [/employees,\App\Controllers\employeesController.deleteAll,DELETE]
  delete_bills: [/bills,\App\Controllers\billsController.deleteAll,DELETE]
  delete_accounts: [/accounts, \App\Controllers\accountsController.deleteAll,DELETE]
